INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1012', 3, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1013', 1, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1014', 4, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1015', 2, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1016', 2, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1001', 1, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1002', 1, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1003', 1, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1004', 0, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1005', 2, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1006', 2, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1007', 2, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1008', 2, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1009', 2, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1010', 2, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1011', 1, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1012', 1, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1013', 1, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1014', 1, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1015', 2, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('A1016', 2, '신도림역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1001', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1002', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1003', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1004', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1005', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1006', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1007', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1008', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1009', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1010', 0, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1011', 1, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1012', 1, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1013', 1, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1014', 1, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1015', 2, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('B1016', 2, '신도림동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1001', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1002', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1003', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1004', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1005', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1006', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1007', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1008', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1009', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1010', 0, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1011', 1, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1012', 1, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1013', 1, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1014', 1, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1015', 2, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('C1016', 2, '구로역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1001', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1002', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1003', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1004', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1005', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1006', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1007', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1008', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1009', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1010', 0, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1011', 1, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1012', 1, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1013', 1, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1014', 1, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1015', 2, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('D1016', 2, '구로5동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1001', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1002', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1003', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1004', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1005', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1006', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1007', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1008', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1009', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1010', 0, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1011', 1, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1012', 1, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1013', 1, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1014', 1, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1015', 2, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('E1016', 2, '여의도역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1001', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1002', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1003', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1004', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1005', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1006', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1007', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1008', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1009', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1010', 0, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1011', 1, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1012', 1, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1013', 1, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1014', 1, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1015', 2, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('F1016', 2, '여의나루역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1001', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1002', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1003', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1004', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1005', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1006', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1007', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1008', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1009', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1010', 0, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1011', 1, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1012', 1, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1013', 1, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1014', 1, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1015', 2, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('G1016', 2, '당산역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1001', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1002', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1003', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1004', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1005', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1006', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1007', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1008', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1009', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1010', 0, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1011', 1, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1012', 1, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1013', 1, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1014', 1, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1015', 2, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('H1016', 2, '당산2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1001', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1002', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1003', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1004', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1005', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1006', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1007', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1008', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1009', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1010', 0, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1011', 1, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1012', 1, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1013', 1, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1014', 1, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1015', 2, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('I1016', 2, '노량진역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1001', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1002', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1003', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1004', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1005', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1006', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1007', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1008', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1009', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1010', 0, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1011', 1, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1012', 1, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1013', 1, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1014', 1, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1015', 2, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('J1016', 2, '노량진2동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1001', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1002', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1003', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1004', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1005', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1006', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1007', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1008', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1009', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1010', 0, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1011', 1, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1012', 1, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1013', 1, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1014', 1, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1015', 2, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('K1016', 2, '이수역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1001', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1002', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1003', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1004', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1005', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1006', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1007', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1008', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1009', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1010', 0, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1011', 1, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1012', 1, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1013', 1, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1014', 1, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1015', 2, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('L1016', 2, '남성역지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1001', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1002', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1003', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1004', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1005', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1006', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1007', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1008', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1009', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1010', 0, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1011', 1, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1012', 1, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1013', 1, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1014', 1, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1015', 2, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('M1016', 2, '망원1동주민센터지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1001', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1002', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1003', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1004', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1005', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1006', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1007', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1008', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1009', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1010', 0, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1011', 1, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1012', 1, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1013', 1, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1014', 1, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1015', 2, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('N1016', 2, '망원한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1001', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1002', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1003', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1004', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1005', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1006', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1007', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1008', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1009', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1010', 0, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1011', 1, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1012', 1, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1013', 1, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1014', 1, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1015', 2, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('O1016', 2, '하늘공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1001', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1002', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1003', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1004', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1005', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1006', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1007', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1008', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1009', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1010', 0, '난지한강공원지점');

INSERT INTO SCOTT.BICYCLEINFO
  (BYNO, BSTATUS, JIJEOM)
VALUES
  ('P1011', 1, '난지한강공원지점');

